export const queryKeys = {
  backendHealth: ["backend-health"] as const,
  embeddingsStatus: ["embeddings-status"] as const,
  coauthorshipStatus: ["coauthorship-status"] as const,
  semanticGraphStatus: ["semantic-graph-status"] as const,
  publicationsPreview: ["publications-preview"] as const,
  publications: (filters: Record<string, unknown>) => ["publications", filters] as const,
  publication: (id: string) => ["publication", id] as const,
  publicationAuthors: (id: string) => ["publication-authors", id] as const,
  publicationOrganizations: (id: string) => ["publication-organizations", id] as const,
  publicationEmbedding: (id: string) => ["publication-embedding", id] as const,
  researchers: (filters: Record<string, unknown>) => ["researchers", filters] as const,
  researcher: (id: string) => ["researcher", id] as const,
  researcherAffiliations: (id: string) => ["researcher-affiliations", id] as const,
  organizations: (filters: Record<string, unknown>) => ["organizations", filters] as const,
  organization: (id: string) => ["organization", id] as const,
  dashboardCounts: ["dashboard-counts"] as const,
  quickSearch: (query: string) => ["quick-search", query] as const,
  coauthorshipGraph: (filters: Record<string, unknown>) =>
    ["coauthorship-graph", filters] as const,
  semanticGraph: (filters: Record<string, unknown>) => ["semantic-graph", filters] as const,
  coauthorshipMetrics: ["coauthorship-metrics"] as const,
  semanticMetrics: ["semantic-metrics"] as const,
  coauthorshipNode: (id: string) => ["coauthorship-node", id] as const,
  semanticNode: (id: string) => ["semantic-node", id] as const,
  adminSeedStatus: ["admin", "seed", "status"] as const,
  adminNormalizationStatus: ["admin", "normalization", "status"] as const,
  adminNormalizationFindings: ["admin", "normalization", "findings"] as const,
  adminEmbeddingsProvider: ["admin", "embeddings", "provider"] as const,
  adminEmbeddingsStatus: ["admin", "embeddings", "status"] as const,
  adminCoauthorshipStatus: ["admin", "coauthorship", "status"] as const,
  adminSemanticStatus: ["admin", "semantic", "status"] as const,
} as const;
